#!/bin/sh

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

install_deps() {
    yay -S --noconfirm --needed \
        lsd fzf zoxide zsh bat less btop \
        ttf-space-mono-nerd ttf-ms-win10-auto yt-dlp bind nmap youtube-music \
        jellyfin-mpv-shim python-pystray noto-fonts noto-fonts-emoji noto-fonts-cjk \
        gnome-text-editor ufw encfs seahorse gvfs-smb amdvlk reflector \
        neovim ntfs-3g nautilus-code nautilus-open-any-terminal mpv tailscale \
        unzip tmux go bluetooth-autoconnect btop powertop \
        yazi p7zip fd ffmpegthumbnailer chafa poppler 
}

update_user_dirs() {
    echo ":: User dirs"
    xdg-user-dirs-update
}

aj_disk() {
    uuid="a670b2de-99ca-43e3-8c34-3fc50150c12e"
    if sudo blkid | grep $uuid >/dev/null 2>&1; then
        sudo mkdir /mnt/AJ/
        user=$(whoami)
        sudo chown $user:$user /mnt/AJ/
        echo -ne "
# AJ
UUID=$uuid /mnt/AJ btrfs defaults 0 2
" | sudo tee -a /etc/fstab

        sudo mount -a
        sudo systemctl daemon-reload

        ln -sf /mnt/AJ $HOME/AJ
        ln -sf /mnt/AJ/{Documents,Downloads,Pictures,Projects,Videos} $HOME

        cp -r /mnt/AJ/.ssh/ $HOME


        mkdir ~/.hehe
    fi
}

plymouth_install() {
    yay -S --noconfirm plymouth plymouth-theme-archlinux
    if pacman -Q grub >/dev/null 2>&1; then
        sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& splash/' /etc/default/grub
        sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub

        sudo sed -i '/echo "\$message"/d' /etc/grub.d/10_linux

        sudo grub-mkconfig -o /boot/grub/grub.cfg
    fi

    sudo sed -i '/^HOOKS/s/udev/& plymouth/' /etc/mkinitcpio.conf

    sudo plymouth-set-default-theme -R archlinux
}

evremap_install() {
    yay -S --noconfirm evremap
    sudo cp -f "${SCRIPT_DIR}/configs/evremap/evremap.toml" /etc
    sudo cp -f "${SCRIPT_DIR}/configs/evremap/evremap.service" /etc/systemd/user
    sudo systemctl enable --now evremap
}

rog_install() {
    if ! pacman -Q cachyos-mirrorlist >/dev/null 2>&1; then
        sudo pacman-key --recv-keys 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
        sudo pacman-key --finger 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
        sudo pacman-key --lsign-key 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
        sudo pacman-key --finger 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35

        wget "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8b15a6b0e9a3fa35" -O /tmp/g14.sec
        sudo pacman-key -a /tmp/g14.sec
        rm /tmp/g14.sec

        echo -ne "
 [g14]
 Server = https://arch.asus-linux.org
 " | sudo tee -a /etc/pacman.conf
    fi

    sudo pacman -Suy --noconfirm asusctl power-profiles-daemon supergfxctl switcheroo-control
    sudo systemctl enable --now power-profiles-daemon supergfxd switcheroo-control

    asusctl -c 60
    asusctl aura static -c 614F9A
    echo "Skip if fail"
}

rog_setup() {
    if hostnamectl status | grep ROG >/dev/null 2>&1; then
        rog_install
        evremap_install
    fi
}

cp_configs() {
    find $SCRIPT_DIR/config/.configs -maxdepth 1 -mindepth 1 |
        while read i; do
            rm -rf "${HOME:-/home/$USER}/.config/$(basename "$i")"
            cp -rf "$i" "${HOME:-/home/$USER}/.config/$(basename "$i")"
        done
}

main() {
    install_deps
    update_user_dirs
    plymouth_install
    rog_setup
    aj_disk
}


if [ "$1"  == '-A' ]; then
    main
fi